name: pull request

on: [pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    outputs:
      cache_key: ${{ steps.cache_key.outputs.cache_key }}

    steps:
      - uses: actions/checkout@v3
      - id: cache_key
        run: echo "cache_key=${{ hashFiles('**/**') }}-v1" >> "$GITHUB_OUTPUT"
      - uses: actions/cache@v3
        id: cache
        with:
          path: .
          key: ${{ steps.cache_key.outputs.cache_key }}
      - if: steps.cache.outputs.cache-hit != true
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - if: steps.cache.outputs.cache-hit != true
        run: npm install
      - if: steps.cache.outputs.cache-hit != true
        env:
          ELEVENTY_ENV: production
        run: npm run build

  pa11y-scan:
    # Pinned to 20.04 because pa11y-ci fails to run on 22.04
    # See the discussion on https://github.com/pa11y/pa11y-ci/issues/198
    # and https://github.com/pa11y/pa11y/issues/651
    runs-on: ubuntu-20.04
    before_script:
      - apt-get update
      - apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2
        libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4
        libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0
        libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1
        libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1
        libxss1 libxtst6 ca-certificates fonts-liberation libnss3 lsb-release
        xdg-utils wget
    steps:
      - uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install node dependencies
        run: npm install
      - name: Refresh assets
        run: npm run assets:refresh
      - name: Accessibility scan
        run: npm run test:pa11y-ci

  validate_html:
    needs: [build]
    name: validate html
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache/restore@v3
        with:
          key: ${{ needs.build.outputs.cache_key }}
          path: .
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm run test:html-validation


  check_links:
    needs: [build]
    name: Check all links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache/restore@v3
        with:
          key: ${{ needs.build.outputs.cache_key }}
          path: .
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Test all links
        run: npm run test:links

  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install node dependencies
        run: npm install
      - name: Run eslint
        run: npm run lint

